name: Deploy to GitHub Pages

on:
  push:
    branches:
      - website  # Trigger when you push to this branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # Since you are on the website branch, deploy the root
          branch: gh-pages # This creates/updates a hidden branch for the site
