_target_: evals.datasets.nyu.NYU
train_path: /sci/labs/sagieb/davidjoseph/probe3d_change_name_for_import_issues_from_splat_and_distill_dir/data/nyu_geonet
test_path: /sci/labs/sagieb/davidjoseph/probe3d_change_name_for_import_issues_from_splat_and_distill_dir/data/nyuv2/nyuv2_snorm_all.pkl
image_mean: imagenet
augment_train: True
center_crop: True
